title: Thinking Rocks
author:
  name: Henry Perschk
  url: ""
  email: ""
description: "" # multiple lines allowed

exclude:
  - .jektex-cache

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  

permalink: /b/:categories/:slug

favicon: "favicon.png"

# theme: lanyon
# remote_theme: riggraz/no-style-please

sass:
  style: compressed

plugins:
  - jektex
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

google_analytics_id: # UA-XXXX-Y
